### PR TITLE
Fixed some bugs and added in ability to keep UI shown while rotating

### PR DESCRIPTION
**Pull request by mitchelldmccollum**

### CODE REVIEW

**Comment by maikramer** [comment]
Could you resolve the conflicts first? i think you are using a older version of unity, 2018.3.0, update to unity 2018.3.6 then update your pull request. Thanks.

**Comment by maikramer** [comment]
You can solve also making a git reset then making a commit with the cs files only.

**Comment by mitchelldmccollum** [comment]
I think i fixed it. I had to do some adjustments in the scene as well

**Comment by maikramer** [comment]
Ah ok, now only the main scene is conflicting, i supose it's about the version you are using, now i'm in my job, oil and gas company, i will come back home in a couple of days, then i can look about this.

**Comment by mitchelldmccollum** [comment]
The scene conflict is because I added a bool that i needed to hook up directly into the scene for an object reference. I chose to do it this way because I felt it would be easier then trying to find that specific object. also my commit I just did added a reset to defaults for each map type so if you mess the map up to much you can go back to the beginning before you messed it up.

**Comment by maikramer** [comment]
I understand, i'm really happy with your help, really, i never had a sucessful repository like this one, it's a pleasure to merge your commit, i will merge it manually at home, today i'm going to my city for a break then i can solve this conflict.

**Comment by mitchelldmccollum** [comment]
I also have a batching branch, if you want i can look into merging this later as well. At work we use this to batch large amounts of products though the tool so all I need to do is hook it up to the current UI and it is useable. I do also have another branch for a new UI we could talk about.

**Pull request merged**
